<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>77271423-9c00-45e3-a72d-f9a013b4d4eb</UserSecretsId>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Universidad.Aplicacion\Universidad.Aplicacion.csproj" />
    <ProjectReference Include="..\Universidad.Infraestructura\Universidad.Infraestructura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensiones\" />
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>
